name: App Lint

on:
  pull_request:
    paths:
      - src/

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version:21.x

      - name: Install deps
        run: npm install

      - name: Run lint
        run: npm run lint