name: App Lint

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install deps
        run: npm install

      - name: Run lint
        run: npm run lint
